"""initial schema

Revision ID: 4632c1f1966b
Revises: 
Create Date: 2026-03-26 09:50:36.027883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4632c1f1966b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet_metadata',
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('netuid')
    )
    op.create_table('subnet_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('capital_score', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('efficiency_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('dev_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score_version', sa.String(length=16), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_scores_computed_at'), 'subnet_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_subnet_scores_netuid'), 'subnet_scores', ['netuid'], unique=False)
    op.create_index('ix_subnet_scores_netuid_computed_at', 'subnet_scores', ['netuid', 'computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subnet_scores_netuid_computed_at', table_name='subnet_scores')
    op.drop_index(op.f('ix_subnet_scores_netuid'), table_name='subnet_scores')
    op.drop_index(op.f('ix_subnet_scores_computed_at'), table_name='subnet_scores')
    op.drop_table('subnet_scores')
    op.drop_table('subnet_metadata')
    # ### end Alembic commands ###
